In [2]:

periodo=202201
periodo_fin=202202



country_config = {  'CL': {'depth1':  7,'learning_rate1':  0.180159, 'n_estimators1': 324, 'dol': 900,
                           'depth2': 10,'learning_rate2':  0.114432, 'n_estimators2': 300},
                    'BO': {'depth1':  9,'learning_rate1':  0.078936, 'n_estimators1': 242, 'dol': 8,
                           'depth2': 10,'learning_rate2':  0.081538, 'n_estimators2': 365},
                    'SV': {'depth1': 10,'learning_rate1':  0.111690, 'n_estimators1': 242, 'dol': 1,
                           'depth2': 12,'learning_rate2':  0.094857, 'n_estimators2': 301},
                    'PA': {'depth1': 10,'learning_rate1':  0.069030, 'n_estimators1': 242, 'dol': 1,
                           'depth2': 11,'learning_rate2':  0.199000, 'n_estimators2': 257},
                    'PE': {'depth1': 10,'learning_rate1':  0.112186, 'n_estimators1': 205, 'dol': 4,
                           'depth2': 11,'learning_rate2':  0.158699, 'n_estimators2': 301},
                    'CO': {'depth1':  9,'learning_rate1':  0.092240, 'n_estimators1': 341, 'dol': 4500,
                           'depth2': 10,'learning_rate2':  0.211300, 'n_estimators2': 306},
                    'CR': {'depth1': 10,'learning_rate1':  0.084432, 'n_estimators1': 340, 'dol': 570,
                           'depth2': 10,'learning_rate2':  0.124635, 'n_estimators2': 302},
                    'MX': {'depth1':  9,'learning_rate1':  0.153500, 'n_estimators1': 227, 'dol': 20,
                           'depth2': 11,'learning_rate2':  0.078430, 'n_estimators2': 301},
                    'EC': {'depth1':  8,'learning_rate1':  0.173996, 'n_estimators1': 327, 'dol': 1,
                           'depth2': 10,'learning_rate2':  0.199140, 'n_estimators2': 364},
                    'GT': {'depth1': 10,'learning_rate1':  0.121033, 'n_estimators1': 206, 'dol': 7.7,
                           'depth2': 10,'learning_rate2':  0.110195, 'n_estimators2': 255},
                    'DO': {'depth1': 10,'learning_rate1':  0.069029, 'n_estimators1': 242, 'dol': 55,
                           'depth2': 11,'learning_rate2':  0.105960, 'n_estimators2': 365},
                    'PR': {'depth1':  8,'learning_rate1':  0.153454, 'n_estimators1': 172, 'dol': 1,
                           'depth2':  8,'learning_rate2':  0.162866, 'n_estimators2': 406}}

In [51]:

def data():
    params=[]
    country='CL'
    datos={
    'dol':country_config[country]['dol'],
    'periodo':periodo,
    'periodo_fin':periodo_fin
    },
    config={
        'flg':1,
        'flg2':2
    }
    params.append(country)
    params.append(datos)
    params.append(config)
   
    
    return params



datos=data()
print(datos)

['CL', ({'dol': 900, 'periodo': 202201, 'periodo_fin': 202202},), {'flg': 1, 'flg2': 2}]

In [60]:
def main():
     pais =data()[0]
     params=data()[1]
     params=params[0]
     dol=params['dol']
     
     
     
   
     
     
     return dol



dato=main()
print(dato)

900

In [52]:
# Crear la tupla con el diccionario
mi_tupla = ({'dol': 900, 'periodo': 202201, 'periodo_fin': 202202},)

# Acceder al diccionario dentro de la tupla utilizando su Ã­ndice
mi_diccionario = mi_tupla[0]

# Acceder a los valores del diccionario utilizando la sintaxis de acceso a claves de diccionario
valor_dol = mi_diccionario['dol']
valor_periodo = mi_diccionario['periodo']
valor_periodo_fin = mi_diccionario['periodo_fin']

# Imprimir los valores obtenidos
print(valor_dol, valor_periodo, valor_periodo_fin)

900 202201 202202

In [11]:
PATH_MODELS = 'forecastdss/models/'
PATH_LOCAL = '/local_storage'
import os



import os

def save_model_local(country,period):
    file_train = 'train.pkl'
    foldername = PATH_MODELS + country + '/' + period
  
    path_local = os.path.join(foldername, file_train)
    path_local = path_local.replace("\\", "/")
    
    return path_local

In [12]:
  
local = save_model_local('CL',str(202204))  
print(local)

forecastdss/models/CL/202204/train.pkl

In [13]:
PATH_MODELS = 'forecastdss/models/'
PATH_MODELS_RESULTS = 'results/'


def resul_path(country,dataframe,period):
    PATH_FILE=PATH_MODELS + PATH_MODELS_RESULTS +country+ '/' + period
    file=dataframe+'.csv'
    path_local = os.path.join(PATH_FILE, file)
    path_local = path_local.replace("\\", "/")
    return path_local


dato=resul_path('CL','data',str(202201))
print(dato)

forecastdss/models/results/CL/202201/data.csv

In [117]:
import pandas as pd
PATH_MODELS = 'forecastdss/models/'
PATH_MODELS_RESULTS = 'results/'
def df_read_from_s3(filename,country):
    bucket='belc-bigdata-models-dlk-dev'
    PAHT_INI=PATH_MODELS+PATH_MODELS_RESULTS+country
    path_local = os.path.join(PAHT_INI, filename)
    path_local = path_local.replace("\\", "/")
    
    """
    Read csv file from s3
    :param bucket: bucket name
    :param path: root file in s3
    :return: Data frame
    """
    s3 = get_credentials()
    obj = s3.get_object(Bucket=bucket, Key=path_local)
    df = pd.read_csv(io.BytesIO(obj['Body'].read()))
    return df



test=df_read_from_s3('archivo.csv','CL')
print(test)

forecastdss/models/results/CL/archivo.csv

In [29]:
import json 
import pandas as pd

In [30]:

with open('..\data\jsonRequest.json', 'r') as archivo:
    objeto_python = json.load(archivo)

In [32]:
pais=objeto_python['Pais']
periodo=objeto_python['Periodo']
ofertas=objeto_python['ProductosOfertas']
apoyo=objeto_python['ApoyoOfertas']

In [33]:
dfofertas=pd.DataFrame(ofertas)
dfapoyo=pd.DataFrame(apoyo)

In [34]:
dfofertas

,COD_PERIODO,ID_COMPONENTE,COD_PAIS,ALCANCE,COD_CATALOGO,ID_TIPO_SUBESTRATEGIA,ID_OFERTA,ID_GRUPO,ES_GRUPO_PADRE,ID_SUB_GRUPO,...,FLAGDISCOVER,FLAGFOTOPRODUCTO,FLAGFOTOMODELO,NROPAGINAS,CICLO_DE_VIDA,N_CAMPAIGN,FLAG_RXP,NUM_PAGINA,CODIGO_FRANJA,EXPOSICION
0,202305,10892858,CL,MASIVO,24,999,7401927,8662167,1,8662167,...,0,1,0,2,Linea,36,0,25,None,6.25
1,202305,10892863,CL,MASIVO,24,999,7401927,8662169,1,8662169,...,0,1,0,2,Linea,36,0,25,None,6.25
2,202305,10892861,CL,MASIVO,24,999,7401927,8662168,1,8662168,...,0,1,0,2,Linea,36,0,25,None,6.25
3,202305,10892773,CL,MASIVO,24,3,7401919,8662143,0,8662143,...,0,1,0,1,Linea,36,0,30,None,6.25
4,202305,10892856,CL,MASIVO,24,999,7401927,8662166,1,8662166,...,0,1,0,2,Nuevo,1,0,23,None,87.50
5,202305,10892866,CL,MASIVO,24,999,7401927,8662170,1,8662170,...,0,1,0,2,Nuevo,1,0,25,None,87.50
6,202305,10892859,CL,MASIVO,24,999,7401927,8662167,1,8662167,...,0,1,0,2,Nuevo,1,0,25,None,87.50
7,202305,10892864,CL,MASIVO,24,999,7401927,8662169,1,8662169,...,0,1,0,2,Nuevo,1,0,25,None,87.50
8,202305,10892862,CL,MASIVO,24,999,7401927,8662168,1,8662168,...,0,1,0,2,Nuevo,1,0,25,None,87.50
9,202305,10892996,CL,MASIVO,24,999,7401943,8662222,1,8662222,...,0,1,0,1,Linea,36,0,19,None,16.70
10,202305,10892999,CL,MASIVO,24,999,7401943,8662223,1,8662223,...,0,1,0,1,Linea,36,0,19,None,16.70
11,202305,10892993,CL,MASIVO,24,999,7401943,8662221,1,8662221,...,0,1,0,1,Linea,36,0,19,None,16.70
12,202305,10892997,CL,MASIVO,24,999,7401943,8662222,1,8662222,...,0,1,0,1,Linea,36,0,19,None,16.70
13,202305,10892994,CL,MASIVO,24,999,7401943,8662221,1,8662221,...,0,1,0,1,Linea,36,0,19,None,16.70
14,202305,10893000,CL,MASIVO,24,999,7401943,8662223,1,8662223,...,0,1,0,1,Linea,36,0,19,None,16.70
15,202305,10892995,CL,MASIVO,24,999,7401943,8662221,1,8662221,...,0,1,0,1,Linea,36,0,19,None,16.70
16,202305,10892998,CL,MASIVO,24,999,7401943,8662222,1,8662222,...,0,1,0,1,Linea,36,0,19,None,16.70
17,202305,10893001,CL,MASIVO,24,999,7401943,8662223,1,8662223,...,0,1,0,1,Linea,36,0,19,None,16.70
18,202305,10892777,CL,MASIVO,24,3,7401919,8662144,1,8662144,...,0,1,0,1,Linea,23,0,30,None,12.50
19,202305,10892765,CL,MASIVO,24,2,7401916,8662134,1,8662134,...,0,1,0,1,Linea,36,0,19,None,16.70
20,202305,10892774,CL,MASIVO,24,3,7401919,8662144,1,8662144,...,0,1,0,1,Linea,23,0,30,None,12.50
21,202305,10891974,CL,MASIVO,09,1,7401255,8661455,1,8661455,...,0,1,1,2,Linea,36,0,14,None,25.00
22,202305,10892764,CL,MASIVO,24,2,7401916,8662134,1,8662134,...,0,1,0,1,Linea,36,0,19,None,16.70
23,202305,10892778,CL,MASIVO,24,5,7401920,8662145,1,8662145,...,0,0,0,0,None,0,0,12,None,NaN
24,202305,10892776,CL,MASIVO,24,3,7401919,8662144,1,8662144,...,0,1,0,1,Linea,23,0,30,None,12.50
25,202305,10892775,CL,MASIVO,24,3,7401919,8662144,1,8662144,...,0,1,0,1,Linea,23,0,30,None,12.50
26,202305,10892643,CL,MASIVO,13,7,7401848,8662064,1,8662064,...,0,1,0,2,Linea,36,0,116,None,100.00
27,202305,10892644,CL,MASIVO,13,7,7401848,8662064,1,8662064,...,0,1,0,2,Linea,36,0,116,None,6.25
28,202305,10892860,CL,MASIVO,24,999,7401927,8662168,1,8662168,...,0,1,0,2,Linea,36,0,25,None,6.25
29,202305,10892857,CL,MASIVO,24,999,7401927,8662167,1,8662167,...,0,1,0,2,Linea,36,0,25,None,6.25
30,202305,10892865,CL,MASIVO,24,999,7401927,8662170,1,8662170,...,0,1,0,2,Linea,36,0,25,None,6.25
31,202305,10892300,CL,MASIVO,10,1,7401538,8661723,1,8661723,...,0,0,1,1,Linea,0,0,100,None,100.00
32,202305,10892766,CL,MASIVO,24,2,7401916,8662134,1,8662134,...,0,1,0,1,Linea,36,0,19,None,16.70
33,202305,10892300,CL,MASIVO,10,1,7401538,8661723,1,8661723,...,0,1,1,1,Linea,0,0,100,None,100.00
34,202305,10892300,CL,MASIVO,10,1,7401538,8661723,1,8661723,...,0,0,1,1,Linea,0,0,100,None,100.00

In [1]:
import os

In [16]:
import os
import pandas as pd
PATH='models'
def obtener_ultimo_periodo(pais, archivo_csv):
    ruta_pais = os.path.join('D:\Projects\data analytics\models', pais)
    ruta_pais = ruta_pais.replace("\\", "/")
    periodos = [x for x in os.listdir(ruta_pais) if os.path.isdir(os.path.join(ruta_pais, x))]
    ultimo_periodo = sorted(periodos)[-1]
    ruta_archivo = os.path.join(ruta_pais, ultimo_periodo, archivo_csv)
    data=pd.read_csv(ruta_archivo,delimiter=';')
    return data

In [17]:
dato=obtener_ultimo_periodo('PE','data.csv')
print(dato)

  country  period
0      pe  202203